-- =============================================
-- Quản Lý Đại Lý - Database Schema
-- SE104 - Nhập môn Công nghệ Phần mềm
-- =============================================

CREATE DATABASE IF NOT EXISTS quan_ly_dai_ly
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE quan_ly_dai_ly;

-- =============================================
-- NHÓM 1: NGƯỜI DÙNG & PHÂN QUYỀN
-- =============================================

CREATE TABLE IF NOT EXISTS NHOMNGUOIDUNG (
  MaNhom INT AUTO_INCREMENT PRIMARY KEY,
  TenNhom VARCHAR(50) NOT NULL UNIQUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS NGUOIDUNG (
    TenNguoiDung VARCHAR(30) PRIMARY KEY,
    MatKhau VARCHAR(100),
    MaNhom INT,
    FOREIGN KEY (MaNhom) REFERENCES NHOMNGUOIDUNG(MaNhom)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CHUCNANG (
  MaChucNang INT AUTO_INCREMENT PRIMARY KEY,
  TenChucNang VARCHAR(100) NOT NULL,
  TenManHinhDuocLoad VARCHAR(30),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PHANQUYEN (
  MaNhom INT NOT NULL,
  MaChucNang INT NOT NULL,
  Xem BOOLEAN DEFAULT TRUE,
  Them BOOLEAN DEFAULT TRUE,
  Xoa BOOLEAN DEFAULT TRUE,
  Sua BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (MaNhom, MaChucNang),
  FOREIGN KEY (MaNhom) REFERENCES NHOMNGUOIDUNG(MaNhom) ON DELETE CASCADE,
  FOREIGN KEY (MaChucNang) REFERENCES CHUCNANG(MaChucNang) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =============================================
-- NHÓM 2: ĐẠI LÝ
-- =============================================

CREATE TABLE IF NOT EXISTS LOAIDAILY (
  MaLoaiDaiLy INT AUTO_INCREMENT PRIMARY KEY,
  TenLoaiDaiLy VARCHAR(50) NOT NULL,
  TienNoToiDa DECIMAL(15,2) NOT NULL DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS QUAN (
  MaQuan INT AUTO_INCREMENT PRIMARY KEY,
  TenQuan VARCHAR(50) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DAILY (
  MaDaiLy INT AUTO_INCREMENT PRIMARY KEY,
  TenDaiLy VARCHAR(100) NOT NULL,
  MaLoaiDaiLy INT NOT NULL,
  MaQuan INT NOT NULL,
  SDT VARCHAR(15),
  DiaChi VARCHAR(255),
  Email VARCHAR(100),
  NgayTiepNhan DATE NOT NULL,
  TongNo DECIMAL(15,2) DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (MaLoaiDaiLy) REFERENCES LOAIDAILY(MaLoaiDaiLy),
  FOREIGN KEY (MaQuan) REFERENCES QUAN(MaQuan)
) ENGINE=InnoDB;

-- =============================================
-- NHÓM 3: HÀNG HÓA
-- =============================================

CREATE TABLE IF NOT EXISTS DONVITINH (
  MaDVT INT AUTO_INCREMENT PRIMARY KEY,
  TenDVT VARCHAR(30) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MATHANG (
  MaMatHang INT AUTO_INCREMENT PRIMARY KEY,
  TenMatHang VARCHAR(100) NOT NULL,
  MaDVT INT NOT NULL,
  DonGiaHienTai DECIMAL(15,2) NOT NULL,
  TonKho INT DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (MaDVT) REFERENCES DONVITINH(MaDVT)
) ENGINE=InnoDB;

-- =============================================
-- NHÓM 4: GIAO DỊCH
-- =============================================

CREATE TABLE IF NOT EXISTS PHIEUNHAPHANG (
  MaPhieuNhap INT AUTO_INCREMENT PRIMARY KEY,
  NgayLapPhieu DATE NOT NULL,
  TongTien DECIMAL(15,2) DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CHITIET_PHIEUNHAP (
  MaPhieuNhap INT NOT NULL,
  MaMatHang INT NOT NULL,
  SoLuongNhap INT NOT NULL,
  DonGiaNhap DECIMAL(15,2) NOT NULL,
  ThanhTien DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (MaPhieuNhap, MaMatHang),
  FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEUNHAPHANG(MaPhieuNhap) ON DELETE CASCADE,
  FOREIGN KEY (MaMatHang) REFERENCES MATHANG(MaMatHang)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PHIEUXUATHANG (
  MaPhieuXuat INT AUTO_INCREMENT PRIMARY KEY,
  MaDaiLy INT NOT NULL,
  NgayLapPhieu DATE NOT NULL,
  TongTien DECIMAL(15,2) DEFAULT 0,
  TienTra DECIMAL(15,2) DEFAULT 0,
  ConLai DECIMAL(15,2) DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CHITIET_PHIEUXUAT (
  MaPhieuXuat INT NOT NULL,
  MaMatHang INT NOT NULL,
  SoLuongXuat INT NOT NULL,
  DonGiaXuat DECIMAL(15,2) NOT NULL,
  ThanhTien DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (MaPhieuXuat, MaMatHang),
  FOREIGN KEY (MaPhieuXuat) REFERENCES PHIEUXUATHANG(MaPhieuXuat) ON DELETE CASCADE,
  FOREIGN KEY (MaMatHang) REFERENCES MATHANG(MaMatHang)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PHIEUTHUTIEN (
  MaPhieuThu INT AUTO_INCREMENT PRIMARY KEY,
  MaDaiLy INT NOT NULL,
  NgayThuTien DATE NOT NULL,
  SoTienThu DECIMAL(15,2) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy)
) ENGINE=InnoDB;

-- =============================================
-- NHÓM 5: THAM SỐ & BÁO CÁO
-- =============================================

CREATE TABLE IF NOT EXISTS THAMSO (
  SoDaiLyToiDa INT DEFAULT 100,
  TiLeTinhDonGiaXuat DECIMAL(5,2) DEFAULT 1.02,
  ApDungQDKiemTraSoTienThu BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BAOCAODOANHSO (
  MaBCDS INT AUTO_INCREMENT PRIMARY KEY,
  Thang INT NOT NULL,
  Nam INT NOT NULL,
  TongDoanhSo DECIMAL(15,2) DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CHITIET_BAOCAODOANHSO (
    MaBCDS INT,
    MaDaiLy INT,
    SoLuongPhieuXuat INT,
    TongTriGia DECIMAL(15,2),
    TiLe DECIMAL(5,2),
    PRIMARY KEY (MaBCDS, MaDaiLy),
    FOREIGN KEY (MaBCDS) REFERENCES BAOCAODOANHSO(MaBCDS) ON DELETE CASCADE,
    FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BAOCAOCONGNO (
  Thang INT NOT NULL,
  Nam INT NOT NULL,
  MaDaiLy INT NOT NULL,
  NoDau DECIMAL(15,2) DEFAULT 0,
  PhatSinh DECIMAL(15,2) DEFAULT 0,
  NoCuoi DECIMAL(15,2) DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Thang, Nam, MaDaiLy),
  FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy)
) ENGINE=InnoDB;
