-- =============================================
-- Quản Lý Đại Lý - Database Schema
-- SE104 - Nhập môn Công nghệ Phần mềm
-- =============================================

CREATE DATABASE IF NOT EXISTS quan_ly_dai_ly
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE quan_ly_dai_ly;

-- =============================================
-- NHÓM 1: NGƯỜI DÙNG & PHÂN QUYỀN
-- =============================================

CREATE TABLE IF NOT EXISTS NHOMNGUOIDUNG (
  MaNhom INT AUTO_INCREMENT PRIMARY KEY,
  TenNhom NVARCHAR(50) NOT NULL UNIQUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS NGUOIDUNG (
  MaNguoiDung INT AUTO_INCREMENT PRIMARY KEY,
  TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
  MatKhau VARCHAR(255) NOT NULL,
  HoTen NVARCHAR(100) NOT NULL,
  Email VARCHAR(100),
  MaNhom INT NOT NULL,
  TrangThai BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (MaNhom) REFERENCES NHOMNGUOIDUNG(MaNhom)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CHUCNANG (
  MaChucNang INT AUTO_INCREMENT PRIMARY KEY,
  TenChucNang NVARCHAR(100) NOT NULL,
  TenManHinh VARCHAR(100),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PHANQUYEN (
  MaNhom INT NOT NULL,
  MaChucNang INT NOT NULL,
  PRIMARY KEY (MaNhom, MaChucNang),
  FOREIGN KEY (MaNhom) REFERENCES NHOMNGUOIDUNG(MaNhom) ON DELETE CASCADE,
  FOREIGN KEY (MaChucNang) REFERENCES CHUCNANG(MaChucNang) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =============================================
-- NHÓM 2: ĐẠI LÝ
-- =============================================

CREATE TABLE IF NOT EXISTS LOAIDAILY (
  MaLoai INT AUTO_INCREMENT PRIMARY KEY,
  TenLoai NVARCHAR(50) NOT NULL,
  SoNoToiDa DECIMAL(15,2) NOT NULL DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS QUAN (
  MaQuan INT AUTO_INCREMENT PRIMARY KEY,
  TenQuan NVARCHAR(50) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DAILY (
  MaDaiLy INT AUTO_INCREMENT PRIMARY KEY,
  TenDaiLy NVARCHAR(100) NOT NULL,
  MaLoai INT NOT NULL,
  MaQuan INT NOT NULL,
  DienThoai VARCHAR(15),
  DiaChi NVARCHAR(255),
  Email VARCHAR(100),
  NgayTiepNhan DATE NOT NULL,
  TienNo DECIMAL(15,2) DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (MaLoai) REFERENCES LOAIDAILY(MaLoai),
  FOREIGN KEY (MaQuan) REFERENCES QUAN(MaQuan)
) ENGINE=InnoDB;

-- =============================================
-- NHÓM 3: HÀNG HÓA
-- =============================================

CREATE TABLE IF NOT EXISTS DVT (
  MaDVT INT AUTO_INCREMENT PRIMARY KEY,
  TenDVT NVARCHAR(30) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MATHANG (
  MaMatHang INT AUTO_INCREMENT PRIMARY KEY,
  TenMatHang NVARCHAR(100) NOT NULL,
  MaDVT INT NOT NULL,
  SoLuongTon INT DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (MaDVT) REFERENCES DVT(MaDVT)
) ENGINE=InnoDB;

-- =============================================
-- NHÓM 4: GIAO DỊCH
-- =============================================

CREATE TABLE IF NOT EXISTS PHIEUNHAPHANG (
  MaPN INT AUTO_INCREMENT PRIMARY KEY,
  NgayNhap DATE NOT NULL,
  TongTien DECIMAL(15,2) DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CT_PNH (
  MaPN INT NOT NULL,
  MaMatHang INT NOT NULL,
  SoLuong INT NOT NULL,
  DonGiaNhap DECIMAL(15,2) NOT NULL,
  ThanhTien DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (MaPN, MaMatHang),
  FOREIGN KEY (MaPN) REFERENCES PHIEUNHAPHANG(MaPN) ON DELETE CASCADE,
  FOREIGN KEY (MaMatHang) REFERENCES MATHANG(MaMatHang)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PHIEUXUATHANG (
  MaPX INT AUTO_INCREMENT PRIMARY KEY,
  MaDaiLy INT NOT NULL,
  NgayXuat DATE NOT NULL,
  TongTien DECIMAL(15,2) DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CT_PXH (
  MaPX INT NOT NULL,
  MaMatHang INT NOT NULL,
  SoLuong INT NOT NULL,
  DonGiaXuat DECIMAL(15,2) NOT NULL,
  ThanhTien DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (MaPX, MaMatHang),
  FOREIGN KEY (MaPX) REFERENCES PHIEUXUATHANG(MaPX) ON DELETE CASCADE,
  FOREIGN KEY (MaMatHang) REFERENCES MATHANG(MaMatHang)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PHIEUTHUTIEN (
  MaPT INT AUTO_INCREMENT PRIMARY KEY,
  MaDaiLy INT NOT NULL,
  NgayThu DATE NOT NULL,
  SoTienThu DECIMAL(15,2) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy)
) ENGINE=InnoDB;

-- =============================================
-- NHÓM 5: THAM SỐ & BÁO CÁO
-- =============================================

CREATE TABLE IF NOT EXISTS THAMSO (
  MaThamSo INT AUTO_INCREMENT PRIMARY KEY,
  TenThamSo VARCHAR(100) NOT NULL UNIQUE,
  GiaTri VARCHAR(255) NOT NULL,
  MoTa NVARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BAOCAODOANHSO (
  MaBC INT AUTO_INCREMENT PRIMARY KEY,
  Thang INT NOT NULL,
  Nam INT NOT NULL,
  MaDaiLy INT NOT NULL,
  SoPhieuXuat INT DEFAULT 0,
  TongTriGia DECIMAL(15,2) DEFAULT 0,
  TyLe DECIMAL(5,2) DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy),
  UNIQUE KEY uq_bcds (Thang, Nam, MaDaiLy)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BAOCAOCONGNO (
  MaBC INT AUTO_INCREMENT PRIMARY KEY,
  Thang INT NOT NULL,
  Nam INT NOT NULL,
  MaDaiLy INT NOT NULL,
  NoDau DECIMAL(15,2) DEFAULT 0,
  PhatSinh DECIMAL(15,2) DEFAULT 0,
  NoCuoi DECIMAL(15,2) DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy),
  UNIQUE KEY uq_bccn (Thang, Nam, MaDaiLy)
) ENGINE=InnoDB;
